server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/book_test
    username: root
    password: 1234

jwt:
  jwtSecret: ======================jwt=spring===========================
  jwtExpiration: 2 hours